version: '3'
services:
  app:
    build: .
    ports:
      - 3000:3000
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@localhost:5555/db?schema=public
  db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=db
    volumes:
      - ./data:/var/lib/postgresql/data
